config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get '/breweries', to: 'homes#index'
  get '/breweries/new', to: 'homes#index'
  get '/breweries/:id', to: 'homes#index'
  get '/breweries/:id/reviews', to: 'homes#index'


  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :breweries, only: [:index, :create, :show] do
        resources :reviews, only: [:index]
        resources :beers, only: [:index]
      end
      resources :reviews, only: [:create, :destroy, :update] do
        resources :votes, only: [:create]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end

  end

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :breweries, only: [:index, :edit, :update, :destroy]
  end
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  has_many :reviews, dependent: :destroy
  has_many :beers
end

app/controllers/admin/breweries_controller.rb
class Admin::BreweriesController < ApplicationController
  before_action :authorize_user

  def index
    @breweries = Brewery.all
  end

  def destroy
    brewery = Brewery.find(params[:id])
    brewery.destroy
    redirect_to admin_breweries_path
  end

  def edit
    @brewery = Brewery.find(params[:id])
    @state_array = [ 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NE', 'NH', 'NJ',  'NM', 'NV', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY' ]
  end

  def update
    @brewery = Brewery.find(params[:id])

    if @brewery.update(brewery_params)
      redirect_to admin_breweries_path
    else
      @errors = @brewery.errors.full_messages.to_sentence
      @state_array = [ 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NE', 'NH', 'NJ',  'NM', 'NV', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY' ]
      render :edit
    end
  end

  private

  def brewery_params
    params.require(:brewery).permit(:name, :address, :city, :state, :zip, :image)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Must be an admin")
    end
  end
end

app/controllers/api/v1/breweries_controller.rb
class Api::V1::BreweriesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    render json: { breweries: Brewery.all, user: user_signed_in? }
  end

  def show
    average = average_score(params["id"])
    render json: {brewery: Brewery.find(params["id"]), average: average}
  end

  def create
    if user_signed_in?
      new_brewery = Brewery.new(brewery_params)

      if new_brewery.save
        render json: new_brewery
      else
        render json: new_brewery.errors
      end
    else
      render json: {user: "You must be signed in to add a brewery."}
    end
  end

  private

  def average_score(brewery_id)
    brewery = Brewery.find(brewery_id)
    score_total = 0
    review_list = brewery.reviews
    review_list.each do |review|
      score_total += review.rating
    end
    if review_list.length == 0
      return "No reviews"
    end
    score_total / review_list.length
  end

  def brewery_params
    params.require(:brewery).permit(:name, :address, :city, :state, :zip, :image)
  end
end

app/views/admin/breweries/edit.html.erb
<h1>Edit Brewery</h1>
<p><%= @errors %></p>
<%= form_for ([:admin, @brewery]) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.select :state, @state_array %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <%= link_to "Delete", ([:admin, @brewery]), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/admin/breweries/index.html.erb
<h1>Current Breweries</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= brewery.name %></td>
        <td><%= link_to "Edit", edit_admin_brewery_path(brewery) %></td>
        <td><%= link_to "Delete", ([:admin, brewery]), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Admin User Index", admin_users_path %>
 | 
<%= link_to "Brewery Index", breweries_path %>