config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get '/breweries', to: 'homes#index'
  get '/breweries/new', to: 'homes#index'
  get '/breweries/:id', to: 'homes#index'
  get '/breweries/:id/reviews', to: 'homes#index'


  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :breweries, only: [:index, :create, :show] do
        resources :reviews, only: [:index]
        resources :beers, only: [:index]
      end
      resources :reviews, only: [:create, :destroy, :update] do
        resources :votes, only: [:create]
      end
    end

    namespace :admin do
      resources :users, only: [:index, :show, :edit, :update]
    end

  end

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :breweries, only: [:index, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true
  validates :password, length: { minimum: 7 }, on: :create
  validates :password, length: { minimum: 7 }, on: :update, allow_blank: true
  validates :admin, inclusion: { in: [true, false] }

  has_many :reviews
  has_many :votes
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authorize_user

  def index
    @users = User.all
    @current_user = current_user
  end

  def update
    user = User.find(params[:id])
    if user.admin
      user.update(admin: false)
    else
      user.update(admin: true)
    end
    redirect_to admin_users_path
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Must be an admin")
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :authorize_user

  def index
    render json: User.all
  end

  protected

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Must be an Admin")
    end
  end
end

app/views/admin/users/index.html.erb
<h1>Current Users</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>
      <th>Change Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <% if user.admin %>
          <td>Admin</td>
        <% else %>
          <td>Member</td>
        <% end %>
        <% if user.id != @current_user.id %>
          <td><%= link_to "Change Role", admin_user_path(user), method: :patch %></td>
        <% else %>
          <td>Current User</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Admin Brewery Index", admin_breweries_path %>
 | 
<%= link_to "Brewery Index", breweries_path %>